version: '3.4'

services: 
  serverapi:
    build:
      context: ./ServerAPI
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
    - sqlserver
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
    - servernetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        SA_PASSWORD: "068958Long!"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
    volumes:
        - sqlvolume:/var/opt/mssql
    networks:
        - servernetwork
networks:
  servernetwork:
    
volumes:
  sqlvolume: